name: Deploy and Build on DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to DigitalOcean
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        command: ssh --ssh-private-key "${{ secrets.SSH_PRIVATE_KEY }}" "${{ secrets.USER }}"@"${{ secrets.DROPLET_IP }}" "cd /sites/panto/client && git pull origin main && npm install && npm run build"
