name: Deploy and Build on Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Droplet
      uses: appleboy/ssh-action@v0.4.0
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          rsync -avz -e "ssh -i /path/to/your/private/key" ./sites/panto/client/ user@droplet-ip:/path/to/sites/panto/client/
