name: Deploy and Build on Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Build
      run: cd client

    - name: Install dependencies
      working-directory: ./client  # Navigate to the client directory
      run: npm install
