name: Deploy and Build on Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: ./client

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install && echo ${{ secrets.USER }}

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: dop_v1_b0d2f05a420d90b7e2de80d773a9b77aff2e4f661a21003fb0ed7982d44d536e

