name: Deploy and Build on Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: ./client

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
